version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker-build/api/Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://username:passwd!@pg/blog
      CONFIG: ProductionConfig
    ports:
      - "5000:80"
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    user: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 7s
      timeout: 5s
      retries: 5
volumes:
  db-data: