# Generated by Django 3.2.14 on 2022-07-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220713_1900"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name_plural": "Customers"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "Students"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name_plural": "Teachers"},
        ),
    ]
