"""empty message

Revision ID: 228839db247e
Revises: b6cda0b3472a
Create Date: 2022-06-02 15:53:03.489203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228839db247e'
down_revision = 'b6cda0b3472a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
