"""empty message

Revision ID: b6cda0b3472a
Revises: 984f557dd917
Create Date: 2022-06-02 00:08:30.305745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cda0b3472a'
down_revision = '984f557dd917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'user_id')
    # ### end Alembic commands ###
