# Generated by Django 3.2 on 2022-06-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('teacher_id', models.IntegerField()),
                ('date_happenned', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.IntegerField()),
            ],
        ),
    ]
