# Generated by Django 3.2.2 on 2022-06-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_teacher_options'),
        ('lessons', '0002_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(blank=True, to='users.Student'),
        ),
    ]
