# Generated by Django 3.2 on 2022-06-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20220620_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group_id',
        ),
    ]
