# Generated by Django 3.2 on 2022-06-27 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20220626_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date_scheduled', 'teacher']},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_scheduled',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
