# Generated by Django 3.2 on 2022-06-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='lessons.group'),
            preserve_default=False,
        ),
    ]
