# Generated by Django 3.2 on 2022-06-20 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20220620_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgroup',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolgroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.product'),
        ),
    ]
