# Generated by Django 3.2 on 2022-06-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20220620_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolgroup',
            name='product',
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='product',
            field=models.ManyToManyField(blank=True, to='lessons.Product'),
        ),
    ]
