# Generated by Django 3.2 on 2022-06-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20220621_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PtroductType',
            new_name='ProductType',
        ),
    ]
