# Generated by Django 3.2 on 2022-06-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='schoolgroup',
            name='city',
        ),
        migrations.RemoveField(
            model_name='schoolgroup',
            name='product',
        ),
        migrations.RemoveField(
            model_name='schoolgroup',
            name='student',
        ),
        migrations.RemoveField(
            model_name='schoolgroup',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='schoolgroup',
            name='type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='SchoolGroup',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
